apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: 01-pv
          persistentVolumeClaim:
             claimName: 01-pvc
      containers:
        - name: pv-container
          image: nginx
          env:
            - name: secret-01-user
              valueFrom:
                secretKeyRef:
                  name: secret-01
                  key: username
            - name: secret-01-password
              valueFrom:
                secretKeyRef:
                  name: secret-01
                  key: password  
          ports:
            - containerPort: 80
              name: "http-server"
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: 01-pv